# Generated by Django 2.1.3 on 2018-11-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recipe', models.TextField(max_length=1000)),
                ('info', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('create_date', models.DateField()),
            ],
        ),
    ]
