# Generated by Django 2.1.3 on 2018-11-13 18:48

from django.db import migrations

def update_db(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    for article in Article.objects.all():
        article.title = 'Test'
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181113_1830'),
    ]

    operations = [
        migrations.RunPython(update_db)
    ]
