import csv

def study_group():
    with open('names.csv', 'w', newline='') as csvfile:
        fieldnames = ['first_name', 'last_name', 'telegram_tag']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        writer.writerow({'first_name': 'Андрій', 'last_name': 'Станішевський', 'telegram_tag': '@xlibchyk'})
        writer.writerow({'first_name': 'Alexandr', 'last_name': 'Klimach', 'telegram_tag': '@klimach'})
        writer.writerow({'first_name': 'Alexander', 'last_name': 'Kozhokar', 'telegram_tag': '@hey_alex'})
        writer.writerow({'first_name': 'Victor', 'last_name': 'B.', 'telegram_tag': '@sancheezzz'})
        writer.writerow({'first_name': 'Anton', 'last_name': 'Ivanov', 'telegram_tag': None})
        writer.writerow({'first_name': 'Roman', 'last_name': 'Rodomansky', 'telegram_tag': '@romanrodomansky'})
        writer.writerow({'first_name': 'Pavlo', 'last_name': 'Kandiak', 'telegram_tag': '@kandiak_ps'})
        writer.writerow({'first_name': 'Eugene', 'last_name': 'Zabolotny', 'telegram_tag': 'eugenezabolotny'})
        writer.writerow({'first_name': 'Дмитро', 'last_name': 'Bragarnik', 'telegram_tag': '@Sarbai'})
        writer.writerow({'first_name': 'Eugene', 'last_name': 'Semanyshyn', 'telegram_tag': None})
        writer.writerow({'first_name': 'Anton', 'last_name': 'Dotsenko', 'telegram_tag': None})
        writer.writerow({'first_name': 'Ruslan', 'last_name': 'Karelov', 'telegram_tag': None})
        writer.writerow({'first_name': 'Ostap', 'last_name': 'Rodomansky', 'telegram_tag': '@ostap_rodomansky'})
        writer.writerow({'first_name': 'Igor', 'last_name': 'Tagintsev', 'telegram_tag': '@Ingvar1390'})
        writer.writerow({'first_name': 'Maxim', 'last_name': 'Poleshko', 'telegram_tag': '@Maxim_P'})
        writer.writerow({'first_name': 'Misha', 'last_name': 'Antonkin', 'telegram_tag': 'Cosmander'})
        writer.writerow({'first_name': 'Olga', 'last_name': 'Tregub', 'telegram_tag': None})
        writer.writerow({'first_name': 'Roman', 'last_name': 'Zhovna', 'telegram_tag': None})
        writer.writerow({'first_name': 'Yevheniia', 'last_name': 'Kyryliuk', 'telegram_tag': '@EvgeniaCURSOR'})
        writer.writerow({'first_name': 'Roman', 'last_name': 'Buryy', 'telegram_tag': None})
        writer.writerow({'first_name': 'Almost wise', 'last_name': 'Dragon', 'telegram_tag': '@AlmostWise'})
        writer.writerow({'first_name': 'Natali', 'last_name': 'Maslova', 'telegram_tag': None})
        writer.writerow({'first_name': 'Arthur', 'last_name': 'Veres', 'telegram_tag': '@Artooi'})
        writer.writerow({'first_name': 'Dmytro', 'last_name': 'Melnyk', 'telegram_tag': '@Ekut_v'})
        writer.writerow({'first_name': 'Albert', 'last_name': 'Li', 'telegram_tag': None})
        writer.writerow({'first_name': 'Bohdan', 'last_name': 'Nvakivskyy', 'telegram_tag': None})
        writer.writerow({'first_name': 'Igor', 'last_name': None, 'telegram_tag': '@siriysnlo'})
        writer.writerow({'first_name': 'Anna', 'last_name': None, 'telegram_tag': None})
        writer.writerow({'first_name': 'Igorosha', 'last_name': 'Prororchuk', 'telegram_tag': None})
        writer.writerow({'first_name': 'Jenia', 'last_name': 'Trofimenko', 'telegram_tag': '@jeniaTrofimenko'})
        writer.writerow({'first_name': 'Alina', 'last_name': 'Brygas', 'telegram_tag': None})
        writer.writerow({'first_name': 'Eugen', 'last_name': None, 'telegram_tag': None})
