# Generated by Django 2.1.4 on 2018-12-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsStore', '0002_auto_20181216_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload_img',
            field=models.FileField(blank=True, null=True, upload_to='static/upload_img/'),
        ),
    ]
