# Generated by Django 2.1.4 on 2018-12-17 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsStore', '0003_auto_20181216_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/upload_img/'),
            preserve_default=False,
        ),
    ]
