# Generated by Django 2.1.3 on 2018-12-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20181204_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='created_by',
        ),
    ]
