# Generated by Django 2.1.3 on 2018-12-05 09:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20181204_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
