# Generated by Django 2.1.3 on 2018-12-05 09:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20181205_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
