# Generated by Django 2.1.3 on 2018-12-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-create_at']},
        ),
    ]
