# Generated by Django 2.1.4 on 2018-12-10 19:43

from django.db import migrations


def update_db(apps, schema_editor):
    Todo = apps.get_model('todolist', 'Todo')
    for todo in Todo.objects.all():
        todo.title = "Done" + todo.title
        todo.save()


class Migration(migrations.Migration):
    dependencies = [
        ('todolist', '0008_auto_20181210_1041'),
    ]

    operations = [
        migrations.RunPython(update_db)
    ]
