# Generated by Django 2.1.3 on 2018-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_for_hw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(blank=True, max_length=50, null=True)),
                ('flower_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('flower_image', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
