# Generated by Django 2.1.3 on 2018-12-04 08:24

from django.db import migrations


def update_notes(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all():
        student.notes = "Test notes for user migrations"
        student.save()




class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_notes)
    ]
