# Generated by Django 2.1.3 on 2018-11-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineralModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('formula', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=30)),
                ('luster', models.CharField(max_length=20)),
                ('streak', models.CharField(max_length=20)),
                ('hardness', models.IntegerField()),
                ('density', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_composition', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
