# Generated by Django 2.1.3 on 2018-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockmodel',
            name='avatar',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
