# Generated by Django 2.1.3 on 2018-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologysite', '0002_rockmodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineralmodel',
            name='colour',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='luster',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='streak',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rockmodel',
            name='min_composition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rockmodel',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
