# Generated by Django 2.1.3 on 2018-11-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologysite', '0005_auto_20181122_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineralmodel',
            name='avatar',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='rockmodel',
            name='avatar',
            field=models.ImageField(upload_to='media'),
        ),
    ]
