# Generated by Django 2.1.3 on 2018-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologysite', '0009_auto_20181127_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineralmodel',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='formula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='hardness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='luster',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mineralmodel',
            name='streak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
