# Generated by Django 2.1.3 on 2018-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologysite', '0012_article_rockmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineralmodel',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rockmodel',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
