# Generated by Django 2.1.3 on 2018-12-16 14:22

from django.db import migrations


def update_field(apps, schema_editor):
    Rock = apps.get_model('geologysite', 'RockModel')
    for rock in Rock.objects.all():
        rock.field_task3 = 'Done'
        rock.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geologysite', '0015_rockmodel_field_task3'),
    ]

    operations = [
        migrations.RunPython(update_field)
    ]
