from utils.l2_task1 import Developer, PythonDeveloper, JavaDeveloper, RubyDeveloper
from utils.l2_task2 import *
from utils.l2_task3 import ITCompany

print('####TASK1####')
print('\n')
print('#Task_1.3#')
a = Developer(2, "John")
a.about()
a.write_code()
print('\n')
b = Developer(5, "Mukhamed")
b.about()
b.write_code()
print('\n')
c = Developer(7, "Silvester")
c.about()
c.write_code()
print('\n')
d = PythonDeveloper(7, 'Arnold')
d.about()
d.write_code()
print('\n')
e = JavaDeveloper(2, 'Adolf')
e.about()
e.write_code()
print('\n')
f = RubyDeveloper(5, 'Adolf')
f.about()
f.write_code()
print('\n')

print('#Task_1.4#')
g = Developer(7, 'Roman')
print(g)
h = PythonDeveloper(7, 'Roman')
print(h)
i = JavaDeveloper(7, 'Roman')
print(i)
j = RubyDeveloper(7, 'Roman')
print(j)
print('\n')

print('#Task_1.5#')
developer = PythonDeveloper(5, 'Anton')
developer()
developerR = RubyDeveloper(5, 'Anton')
developerR()
print('\n')
print('\n')
print('####TASK2####')
print('\n')
print(E.mro())
print('\n')
print('####TASK3####')
print('\n')
newemp = JavaDeveloper(1, 'Pavlo')
newemp1 = RubyDeveloper(3, 'Pashko')
newemp2 = PythonDeveloper(10, 'Boris')
newemp3 = Developer(7, 'Adolf')
newemp4 = RubyDeveloper(7, 'Den')
newemp5 = PythonDeveloper(4, 'Den')
itcomp = ITCompany()
itcomp += newemp
itcomp += newemp1
itcomp += newemp2
itcomp += newemp3
itcomp += newemp4
itcomp += newemp5
itcomp.fire_employee('Den')
print(itcomp)